export const motivationalQuotes = [
  { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
  { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { quote: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { quote: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
  { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { quote: "If you can dream it, you can do it.", author: "Walt Disney" },
  { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { quote: "Don’t wait for opportunity. Create it.", author: "George Bernard Shaw" },
  { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
  { quote: "Go the extra mile. It’s never crowded.", author: "Wayne Dyer" },
  { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { quote: "A year from now you may wish you had started today.", author: "Karen Lamb" },
  { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { quote: "Work hard in silence, let success make the noise.", author: "Frank Ocean" },
  { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { quote: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { quote: "Success isn’t about how much money you make. It’s about the difference you make in people’s lives.", author: "Michelle Obama" },
  { quote: "Success doesn’t come from what you do occasionally, it comes from what you do consistently.", author: "Marie Forleo" },
  { quote: "Stay away from those people who try to disparage your ambitions.", author: "Mark Twain" },
  { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { quote: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
  { quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { quote: "Don’t limit your challenges. Challenge your limits.", author: "Jerry Dunn" },
  { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { quote: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
  { quote: "Courage is one step ahead of fear.", author: "Coleman Young" },
  { quote: "Even if you’re on the right track, you’ll get run over if you just sit there.", author: "Will Rogers" },
  { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { quote: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
  { quote: "Learn as if you will live forever, live like you will die tomorrow.", author: "Mahatma Gandhi" },
  { quote: "Great things never come from comfort zones.", author: "Neil Strauss" },
  { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { quote: "Don’t stop when you’re tired. Stop when you’re done.", author: "Marilyn Monroe" },
  { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { quote: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
  { quote: "Your time is limited, don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
  { quote: "Difficult roads often lead to beautiful destinations.", author: "Zig Ziglar" },
  { quote: "Make each day your masterpiece.", author: "John Wooden" },
  { quote: "You can if you think you can.", author: "George Reeves" },
  { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { quote: "You don't need to see the whole staircase, just take the first step.", author: "Martin Luther King Jr." },
  { quote: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
  { quote: "I never dreamed about success. I worked for it.", author: "Estée Lauder" },
  { quote: "Act as if it were impossible to fail.", author: "Dorothea Brande" },
  { quote: "Small deeds done are better than great deeds planned.", author: "Peter Marshall" },
  { quote: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
  { quote: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
  { quote: "Limit your 'always' and your 'nevers'.", author: "Amy Poehler" },
  { quote: "Aim for the moon. If you miss, you may hit a star.", author: "W. Clement Stone" },
  { quote: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { quote: "If opportunity doesn’t knock, build a door.", author: "Milton Berle" },
  { quote: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein" },
  { quote: "Hustle until your haters ask if you’re hiring.", author: "Steve Maraboli" },
  { quote: "Live life as if everything is rigged in your favor.", author: "Rumi" },
  { quote: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { quote: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { quote: "Success is what comes after you stop making excuses.", author: "Luis Galarza" },
  { quote: "Little by little, a little becomes a lot.", author: "Tanzanian Proverb" },
  { quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { quote: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { quote: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { quote: "Set your goals high, and don't stop till you get there.", author: "Bo Jackson" },
  { quote: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
  { quote: "Do the hard jobs first. The easy jobs will take care of themselves.", author: "Dale Carnegie" },
  { quote: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { quote: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { quote: "If you’re going through hell, keep going.", author: "Winston Churchill" },
  { quote: "There is no substitute for hard work.", author: "Thomas Edison" },
  { quote: "Success only comes to those who dare to attempt.", author: "Mallika Tripathi" },
  { quote: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
  { quote: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" }
];
